version: '3'
services:
  app:
    build: .
    ports:
      - "3000:8888"
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  postgres_data: